version: '3.8'

services:
  api:
    build: .
    image: newsscraperapi-flask
    container_name: newsscraperapi-flask
    working_dir: /usr/src/app/news_scraper_api
    command: gunicorn --conf gunicorn_config.py --bind 0.0.0.0:5000 "app:create_app()"
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - mongo_data:/etc/mongo/

  celery:
    build: .
    image: newsscraperapi-celery
    container_name: newsscraperapi-celery
    command: celery --app news_scraper_api.core.tasks.celery worker -B --loglevel=debug --logfile=celery.log
    env_file:
      - ./.env
    depends_on:
      - api
      - redis

  redis:
    image: redis:6.2-alpine

volumes:
  mongo_data:
