from datetime import datetime, timezone

mock_articles = [
    {
        "title": "Title 1",
        "source_name": "BBC",
        "source_unique_id": "id1",
        "url": "url1",
        "img_url": "img_url1",
        "description": "description1",
        "created": datetime.fromtimestamp(1760896328, tz=timezone.utc),
    },
    {
        "title": "Title 2",
        "source_name": "CNN",
        "source_unique_id": "id2",
        "url": "url2",
        "img_url": "img_url2",
        "description": "description2",
        "created": datetime.fromtimestamp(1456393995, tz=timezone.utc),
    },
    {
        "title": "Title 3",
        "source_name": "BBC",
        "source_unique_id": "id3",
        "url": "url3",
        "img_url": "img_url3",
        "description": "description3",
        "created": datetime.fromtimestamp(1313621794, tz=timezone.utc),
    },
    {
        "title": "Title 4",
        "source_name": "Fox News",
        "source_unique_id": "id4",
        "url": "url4",
        "img_url": "img_url4",
        "description": "description4",
        "created": datetime.fromtimestamp(1129174872, tz=timezone.utc),
    },
    {
        "title": "Title 5",
        "source_name": "The Washington Post",
        "source_unique_id": "id5",
        "url": "url5",
        "img_url": "img_url5",
        "description": "description5",
        "created": datetime.fromtimestamp(1105364512, tz=timezone.utc),
    },
    {
        "title": "Title 6",
        "source_name": "The Economist",
        "source_unique_id": "id6",
        "url": "url6",
        "img_url": "img_url6",
        "description": "description6",
        "created": datetime.fromtimestamp(1095387401, tz=timezone.utc),
    },
    {
        "title": "Title 7",
        "source_name": "Fox News",
        "source_unique_id": "id7",
        "url": "url7",
        "img_url": "img_url7",
        "description": "description7",
        "created": datetime.fromtimestamp(1095364512, tz=timezone.utc),
    },
    {
        "title": "Title 8",
        "source_name": "Fox News",
        "source_unique_id": "id8",
        "url": "url8",
        "img_url": "img_url8",
        "description": "description8",
        "created": datetime.fromtimestamp(1086582401, tz=timezone.utc),
    },
    {
        "title": "Title 9",
        "source_name": "BBC",
        "source_unique_id": "id9",
        "url": "url9",
        "img_url": "img_url9",
        "description": "description9",
        "created": datetime.fromtimestamp(1079882999, tz=timezone.utc),
    },
    {
        "title": "Title 10",
        "source_name": "CNN",
        "source_unique_id": "id10",
        "url": "url10",
        "img_url": "img_url10",
        "description": "description10",
        "created": datetime.fromtimestamp(1074882971, tz=timezone.utc),
    },
    {
        "title": "Title 11",
        "source_name": "The Economist",
        "source_unique_id": "id11",
        "url": "url11",
        "img_url": "img_url11",
        "description": "description11",
        "created": datetime.fromtimestamp(1069262919, tz=timezone.utc),
    },
    {
        "title": "Title 12",
        "source_name": "The Washington Post",
        "source_unique_id": "id12",
        "url": "url12",
        "img_url": "img_url12",
        "description": "description12",
        "created": datetime.fromtimestamp(1059262789, tz=timezone.utc),
    },
]
